// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMessagePrivate = `-- name: AddMessagePrivate :one
INSERT INTO message(id,content,parentId,from_id,to_id)VALUES(
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, content, parentid, from_id, to_id, deleted_at, created_at, updated_at
`

type AddMessagePrivateParams struct {
	ID       uuid.UUID
	Content  pgtype.Text
	Parentid pgtype.UUID
	FromID   pgtype.UUID
	ToID     pgtype.UUID
}

func (q *Queries) AddMessagePrivate(ctx context.Context, arg AddMessagePrivateParams) (Message, error) {
	row := q.db.QueryRow(ctx, addMessagePrivate,
		arg.ID,
		arg.Content,
		arg.Parentid,
		arg.FromID,
		arg.ToID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Parentid,
		&i.FromID,
		&i.ToID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addMessagePublic = `-- name: AddMessagePublic :one
INSERT INTO GroupMessage(id,content,group_id,from_id,parent_id)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, content, group_id, from_id, parent_id, created_at, updated_at, deleted_at
`

type AddMessagePublicParams struct {
	ID       uuid.UUID
	Content  pgtype.Text
	GroupID  pgtype.UUID
	FromID   pgtype.UUID
	ParentID pgtype.UUID
}

func (q *Queries) AddMessagePublic(ctx context.Context, arg AddMessagePublicParams) (Groupmessage, error) {
	row := q.db.QueryRow(ctx, addMessagePublic,
		arg.ID,
		arg.Content,
		arg.GroupID,
		arg.FromID,
		arg.ParentID,
	)
	var i Groupmessage
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.GroupID,
		&i.FromID,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMessagesForPrivate = `-- name: GetMessagesForPrivate :many
SELECT id, content, parentid, from_id, to_id, deleted_at, created_at, updated_at FROM message WHERE from_id = $1 AND  to_id = $2 OR from_id = $2 AND to_id= $1
`

type GetMessagesForPrivateParams struct {
	FromID pgtype.UUID
	ToID   pgtype.UUID
}

func (q *Queries) GetMessagesForPrivate(ctx context.Context, arg GetMessagesForPrivateParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesForPrivate, arg.FromID, arg.ToID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Parentid,
			&i.FromID,
			&i.ToID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesForPublic = `-- name: GetMessagesForPublic :many
SELECT id, content, group_id, from_id, parent_id, created_at, updated_at, deleted_at FROM GroupMessage WHERE group_id = $1
`

func (q *Queries) GetMessagesForPublic(ctx context.Context, groupID pgtype.UUID) ([]Groupmessage, error) {
	rows, err := q.db.Query(ctx, getMessagesForPublic, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Groupmessage
	for rows.Next() {
		var i Groupmessage
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.GroupID,
			&i.FromID,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
