// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createRecord = `-- name: CreateRecord :one
INSERT INTO chirp(id,created_at,updated_at,body,user_id)
VALUES(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateRecordParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (Chirp, error) {
	row := q.db.QueryRow(ctx, createRecord, arg.Body, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const deleteRecordByID = `-- name: DeleteRecordByID :exec
DELETE FROM chirp WHERE id = $1
`

func (q *Queries) DeleteRecordByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecordByID, id)
	return err
}

const deleteRecords = `-- name: DeleteRecords :exec
DELETE FROM chirp
`

func (q *Queries) DeleteRecords(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteRecords)
	return err
}

const getAllRecord = `-- name: GetAllRecord :many
SELECT id, created_at, updated_at, body, user_id FROM chirp
`

func (q *Queries) GetAllRecord(ctx context.Context) ([]Chirp, error) {
	rows, err := q.db.Query(ctx, getAllRecord)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecordByID = `-- name: GetRecordByID :one
SELECT id, created_at, updated_at, body, user_id FROM chirp WHERE id = $1
`

func (q *Queries) GetRecordByID(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRow(ctx, getRecordByID, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const getRecordByUserID = `-- name: GetRecordByUserID :one
SELECT id, created_at, updated_at, body, user_id FROM chirp WHERE user_id = $1
`

func (q *Queries) GetRecordByUserID(ctx context.Context, userID uuid.UUID) (Chirp, error) {
	row := q.db.QueryRow(ctx, getRecordByUserID, userID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
