// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createRecord = `-- name: CreateRecord :one
INSERT INTO chirp(id,created_at,updated_at,body,user_id)
VALUES(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateRecordParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, createRecord, arg.Body, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const deleteRecords = `-- name: DeleteRecords :exec
DELETE FROM chirp
`

func (q *Queries) DeleteRecords(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRecords)
	return err
}
