// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForAddMemberList implements pgx.CopyFromSource.
type iteratorForAddMemberList struct {
	rows                 []AddMemberListParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddMemberList) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddMemberList) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].GroupID,
		r.rows[0].MemberID,
	}, nil
}

func (r iteratorForAddMemberList) Err() error {
	return nil
}

func (q *Queries) AddMemberList(ctx context.Context, arg []AddMemberListParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"member_table"}, []string{"group_id", "member_id"}, &iteratorForAddMemberList{rows: arg})
}
