// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addMember = `-- name: AddMember :exec
INSERT INTO member_table(group_id,member_id) VALUES($1,$2)
`

type AddMemberParams struct {
	GroupID  uuid.UUID
	MemberID uuid.UUID
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) error {
	_, err := q.db.Exec(ctx, addMember, arg.GroupID, arg.MemberID)
	return err
}

type AddMemberListParams struct {
	GroupID  uuid.UUID
	MemberID uuid.UUID
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO chat_groups(id,name,description,max_member,current_member)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, name, description, max_member, created_at, updated_at, current_member
`

type CreateGroupParams struct {
	ID            uuid.UUID
	Name          string
	Description   string
	MaxMember     int16
	CurrentMember int16
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (ChatGroup, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.MaxMember,
		arg.CurrentMember,
	)
	var i ChatGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MaxMember,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentMember,
	)
	return i, err
}

const createGroupLeaderRole = `-- name: CreateGroupLeaderRole :one
INSERT INTO member_table(group_id,member_id,role)
VALUES(
    $1,
    $2,
    $3
)
RETURNING id, group_id, member_id, joined_at, role
`

type CreateGroupLeaderRoleParams struct {
	GroupID  uuid.UUID
	MemberID uuid.UUID
	Role     string
}

func (q *Queries) CreateGroupLeaderRole(ctx context.Context, arg CreateGroupLeaderRoleParams) (MemberTable, error) {
	row := q.db.QueryRow(ctx, createGroupLeaderRole, arg.GroupID, arg.MemberID, arg.Role)
	var i MemberTable
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.MemberID,
		&i.JoinedAt,
		&i.Role,
	)
	return i, err
}

const deleteMemFromGroup = `-- name: DeleteMemFromGroup :exec
DELETE FROM member_table WHERE group_id = $1 AND member_id = $2
`

type DeleteMemFromGroupParams struct {
	GroupID  uuid.UUID
	MemberID uuid.UUID
}

func (q *Queries) DeleteMemFromGroup(ctx context.Context, arg DeleteMemFromGroupParams) error {
	_, err := q.db.Exec(ctx, deleteMemFromGroup, arg.GroupID, arg.MemberID)
	return err
}

const getAllGroupInfo = `-- name: GetAllGroupInfo :many
SELECT id,current_member,name,max_member FROM chat_groups
`

type GetAllGroupInfoRow struct {
	ID            uuid.UUID
	CurrentMember int16
	Name          string
	MaxMember     int16
}

func (q *Queries) GetAllGroupInfo(ctx context.Context) ([]GetAllGroupInfoRow, error) {
	rows, err := q.db.Query(ctx, getAllGroupInfo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllGroupInfoRow
	for rows.Next() {
		var i GetAllGroupInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.CurrentMember,
			&i.Name,
			&i.MaxMember,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupInfoByID = `-- name: GetGroupInfoByID :one
SELECT id, name, description, max_member, created_at, updated_at, current_member FROM chat_groups WHERE  id = $1
`

func (q *Queries) GetGroupInfoByID(ctx context.Context, id uuid.UUID) (ChatGroup, error) {
	row := q.db.QueryRow(ctx, getGroupInfoByID, id)
	var i ChatGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MaxMember,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentMember,
	)
	return i, err
}

const getMemFromGroup = `-- name: GetMemFromGroup :one
SELECT id, group_id, member_id, joined_at, role FROM member_table WHERE group_id = $1 AND member_id = $2
`

type GetMemFromGroupParams struct {
	GroupID  uuid.UUID
	MemberID uuid.UUID
}

func (q *Queries) GetMemFromGroup(ctx context.Context, arg GetMemFromGroupParams) (MemberTable, error) {
	row := q.db.QueryRow(ctx, getMemFromGroup, arg.GroupID, arg.MemberID)
	var i MemberTable
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.MemberID,
		&i.JoinedAt,
		&i.Role,
	)
	return i, err
}

const getMemberListByID = `-- name: GetMemberListByID :many
SELECT member_id FROM member_table WHERE group_id = $1
`

func (q *Queries) GetMemberListByID(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getMemberListByID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var member_id uuid.UUID
		if err := rows.Scan(&member_id); err != nil {
			return nil, err
		}
		items = append(items, member_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinGroup = `-- name: JoinGroup :one
INSERT INTO member_table(group_id,member_id)
VALUES(
    $1,
    $2
)
RETURNING id, group_id, member_id, joined_at, role
`

type JoinGroupParams struct {
	GroupID  uuid.UUID
	MemberID uuid.UUID
}

func (q *Queries) JoinGroup(ctx context.Context, arg JoinGroupParams) (MemberTable, error) {
	row := q.db.QueryRow(ctx, joinGroup, arg.GroupID, arg.MemberID)
	var i MemberTable
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.MemberID,
		&i.JoinedAt,
		&i.Role,
	)
	return i, err
}

const searchInfoByName = `-- name: SearchInfoByName :one
SELECT id, name, description, max_member, created_at, updated_at, current_member FROM chat_groups WHERE name = $1
`

func (q *Queries) SearchInfoByName(ctx context.Context, name string) (ChatGroup, error) {
	row := q.db.QueryRow(ctx, searchInfoByName, name)
	var i ChatGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MaxMember,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentMember,
	)
	return i, err
}

const updateGroupCurrentMemberByID = `-- name: UpdateGroupCurrentMemberByID :one
UPDATE  chat_groups SET current_member = (SELECT COUNT(*)FROM member_table WHERE group_id = $1)RETURNING id, name, description, max_member, created_at, updated_at, current_member
`

func (q *Queries) UpdateGroupCurrentMemberByID(ctx context.Context, groupID uuid.UUID) (ChatGroup, error) {
	row := q.db.QueryRow(ctx, updateGroupCurrentMemberByID, groupID)
	var i ChatGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MaxMember,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentMember,
	)
	return i, err
}
