// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO chat_groups(id,name,description,max_member)
VALUES(
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, description, max_member, created_at, updated_at
`

type CreateGroupParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	MaxMember   int16
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (ChatGroup, error) {
	row := q.db.QueryRowContext(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.MaxMember,
	)
	var i ChatGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MaxMember,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
