// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatGroup struct {
	ID            uuid.UUID
	Name          string
	Description   string
	MaxMember     int16
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	CurrentMember int16
}

type Chirp struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
	UserID    uuid.UUID
}

type Groupmessage struct {
	ID        uuid.UUID
	Content   pgtype.Text
	GroupID   pgtype.UUID
	FromID    pgtype.UUID
	ParentID  pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type MemberTable struct {
	ID       uuid.UUID
	GroupID  uuid.UUID
	MemberID uuid.UUID
	JoinedAt pgtype.Timestamp
	Role     string
}

type Message struct {
	ID        uuid.UUID
	Content   pgtype.Text
	Parentid  pgtype.UUID
	FromID    pgtype.UUID
	ToID      pgtype.UUID
	DeletedAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type RefreshToken struct {
	Token     string
	CreatedAt pgtype.Timestamp
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpireAt  time.Time
	RevokedAt pgtype.Timestamp
}

type User struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Email       string
	Password    string
	IsChirpyRed pgtype.Bool
}
