// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ChatGroup struct {
	ID            uuid.UUID
	Name          string
	Description   string
	MaxMember     int16
	CreatedAt     time.Time
	UpdatedAt     time.Time
	CurrentMember int16
}

type Chirp struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
	UserID    uuid.UUID
}

type Groupmessage struct {
	ID        uuid.UUID
	Content   sql.NullString
	GroupID   uuid.NullUUID
	FromID    uuid.NullUUID
	ParentID  uuid.NullUUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type MemberTable struct {
	ID       uuid.UUID
	GroupID  uuid.UUID
	MemberID uuid.UUID
	JoinedAt time.Time
	Role     string
}

type Message struct {
	ID        uuid.UUID
	Content   sql.NullString
	Parentid  uuid.NullUUID
	FromID    uuid.NullUUID
	ToID      uuid.NullUUID
	DeletedAt sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpireAt  time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Email       string
	Password    string
	IsChirpyRed sql.NullBool
}
