// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: position.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAllConfigForUser = `-- name: GetAllConfigForUser :one
SELECT pref FROM EleConfig WHERE user_id = $1
`

func (q *Queries) GetAllConfigForUser(ctx context.Context, userID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAllConfigForUser, userID)
	var pref []byte
	err := row.Scan(&pref)
	return pref, err
}

const getAllUsersConfig = `-- name: GetAllUsersConfig :many
SELECT user_id, pref FROM EleConfig
`

func (q *Queries) GetAllUsersConfig(ctx context.Context) ([]Eleconfig, error) {
	rows, err := q.db.Query(ctx, getAllUsersConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Eleconfig
	for rows.Next() {
		var i Eleconfig
		if err := rows.Scan(&i.UserID, &i.Pref); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePosition = `-- name: SavePosition :one
INSERT INTO EleConfig(user_id,pref)
VALUES($1,$2)RETURNING user_id, pref
`

type SavePositionParams struct {
	UserID uuid.UUID
	Pref   []byte
}

func (q *Queries) SavePosition(ctx context.Context, arg SavePositionParams) (Eleconfig, error) {
	row := q.db.QueryRow(ctx, savePosition, arg.UserID, arg.Pref)
	var i Eleconfig
	err := row.Scan(&i.UserID, &i.Pref)
	return i, err
}
