// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refreshTokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createARefreshToken = `-- name: CreateARefreshToken :one
INSERT INTO refresh_tokens (token,created_at,updated_at,user_id,expire_at,revoked_at)
VALUES(
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    Null
)
RETURNING token, created_at, updated_at, user_id, expire_at, revoked_at
`

type CreateARefreshTokenParams struct {
	Token    string
	UserID   uuid.UUID
	ExpireAt time.Time
}

func (q *Queries) CreateARefreshToken(ctx context.Context, arg CreateARefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createARefreshToken, arg.Token, arg.UserID, arg.ExpireAt)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpireAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT user_id,expire_at FROM refresh_tokens WHERE token = $1
`

type GetRefreshTokenRow struct {
	UserID   uuid.UUID
	ExpireAt time.Time
}

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, token)
	var i GetRefreshTokenRow
	err := row.Scan(&i.UserID, &i.ExpireAt)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = NOW(),updated_at = NOW() WHERE token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, token)
	return err
}
