package aimodels

var dummyConvo = []Message{
	{ID: 1, Speaker: "Jax", Text: "LEO! Pack your bags. We’re leaving in twenty minutes."},
	{ID: 2, Speaker: "Leo", Text: "It’s 11:00 PM on a Tuesday, Jax. Where could we possibly be going?"},
	{ID: 3, Speaker: "Jax", Text: "To the edge of greatness! Or at least the state line."},
	{ID: 4, Speaker: "Leo", Text: "That’s a three-hour drive. I have a 9:00 AM meeting."},
	{ID: 5, Speaker: "Jax", Text: "Cancel it. Tell them you’ve been summoned by the spirit of adventure."},
	{ID: 6, Speaker: "Leo", Text: "I’ll tell them I’ve been kidnapped by a roommate with no impulse control."},
	{ID: 7, Speaker: "Jax", Text: "Same thing. Look, I found this 'unlisted' hiking trail on a Reddit thread."},
	{ID: 8, Speaker: "Leo", Text: "'Unlisted' usually means 'illegal' or 'frequented by bears.'"},
	{ID: 9, Speaker: "Jax", Text: "Or 'undiscovered gems!'"},
	{ID: 10, Speaker: "Leo", Text: "My spreadsheet for the weekend was already finalized. We were going to Costco."},
	{ID: 11, Speaker: "Jax", Text: "Costco? Leo, you’re 28, not 82. Burn the spreadsheet."},
	{ID: 12, Speaker: "Leo", Text: "The spreadsheet is the only thing keeping us from bankruptcy and/or death."},
	{ID: 13, Speaker: "Jax", Text: "I bought a drone. We’re going to film the sunrise from the peak."},
	{ID: 14, Speaker: "Leo", Text: "You can’t fly a drone in a national forest without a permit."},
	{ID: 15, Speaker: "Jax", Text: "Only if you get caught."},
	{ID: 16, Speaker: "Leo", Text: "That is literally the definition of a crime."},
	{ID: 17, Speaker: "Jax", Text: "It’s a 'creative violation.' Big difference."},
	{ID: 18, Speaker: "Leo", Text: "Fine. What’s the terrain like? Do I need my boots?"},
	{ID: 19, Speaker: "Jax", Text: "Just wear sneakers. It’s basically a flat walk."},
	{ID: 20, Speaker: "Leo", Text: "*Reads the Reddit thread* Jax, this says 'vertical scramble.'"},
	{ID: 21, Speaker: "Jax", Text: "Details, details. It’s just a steep walk!"},
	{ID: 22, Speaker: "Leo", Text: "Vertical means up. Like a wall. I am not a mountain goat."},
	{ID: 23, Speaker: "Jax", Text: "You have two legs and a heartbeat. You’re qualified."},
	{ID: 24, Speaker: "Leo", Text: "I’m calling my insurance agent."},
	{ID: 25, Speaker: "Jax", Text: "Too late, I already put your snacks in the car."},
	{ID: 26, Speaker: "Leo", Text: "Which snacks?"},
	{ID: 27, Speaker: "Jax", Text: "Those organic kale chips you hide in the back of the pantry."},
	{ID: 28, Speaker: "Leo", Text: "Those are for emergencies!"},
	{ID: 29, Speaker: "Jax", Text: "This is an emergency. Your life is boring!"},
	{ID: 30, Speaker: "Leo", Text: "My life is 'stable.' There’s a difference."},
	{ID: 31, Speaker: "Jax", Text: "Stable is for horses. Let’s go!"},
	{ID: 32, Speaker: "Leo", Text: "I need to pack my first aid kit."},
	{ID: 33, Speaker: "Jax", Text: "I have Band-Aids."},
	{ID: 34, Speaker: "Leo", Text: "I have a tourniquet and a snake bite extractor."},
	{ID: 35, Speaker: "Jax", Text: "...Why do you have those?"},
	{ID: 36, Speaker: "Leo", Text: "Because of people like you."},
	{ID: 37, Speaker: "Jax", Text: "Fair point. Bring the kit."},
	{ID: 38, Speaker: "Leo", Text: "Are we taking your car or mine?"},
	{ID: 39, Speaker: "Jax", Text: "Yours. Mine is making a 'clunk-clunk-screech' sound."},
	{ID: 40, Speaker: "Leo", Text: "That sounds like a failing CV joint."},
	{ID: 41, Speaker: "Jax", Text: "I thought it was just the car’s way of singing."},
	{ID: 42, Speaker: "Leo", Text: "Cars don’t sing, Jax. They deteriorate."},
	{ID: 43, Speaker: "Jax", Text: "You’re such a buzzkill. It’s endearing, really."},
	{ID: 44, Speaker: "Leo", Text: "I’m the reason we still have a security deposit on this apartment."},
	{ID: 45, Speaker: "Jax", Text: "And I’m the reason we have memories!"},
	{ID: 46, Speaker: "Leo", Text: "Most of those memories involve waiting in an ER lobby."},
	{ID: 47, Speaker: "Jax", Text: "But the nurses know us by name now! That’s VIP status."},
	{ID: 48, Speaker: "Leo", Text: "I’m going to go put on my sensible hiking trousers."},
	{ID: 49, Speaker: "Jax", Text: "'Sensible hiking trousers.' You’re so cute."},
	{ID: 50, Speaker: "Leo", Text: "Stop patronizing me and find the GPS."},
	{ID: 51, Speaker: "Jax", Text: "Who needs GPS? I have a sense of direction."},
	{ID: 52, Speaker: "Leo", Text: "You got lost in a Target last week."},
	{ID: 53, Speaker: "Jax", Text: "That Target was a labyrinth! The aisles make no sense!"},
	{ID: 54, Speaker: "Leo", Text: "It’s a grid, Jax. A literal grid."},
	{ID: 55, Speaker: "Jax", Text: "Whatever. I’ll use my phone until it dies."},
	{ID: 56, Speaker: "Leo", Text: "It’s at 12% right now, isn’t it?"},
	{ID: 57, Speaker: "Jax", Text: "9%. But I have a charger!"},
	{ID: 58, Speaker: "Leo", Text: "Is the charger in the car?"},
	{ID: 59, Speaker: "Jax", Text: "...It might be in the kitchen."},
	{ID: 60, Speaker: "Leo", Text: "Stay there. Don’t touch anything. I’ll handle the logistics."},
	{ID: 61, Speaker: "Jax", Text: "This is why we’re a team. I provide the spark, you provide the fire extinguisher."},
	{ID: 62, Speaker: "Leo", Text: "You provide the arson, I provide the legal defense."},
	{ID: 63, Speaker: "Jax", Text: "Did you pack the binoculars?"},
	{ID: 64, Speaker: "Leo", Text: "Why? Are we birdwatching?"},
	{ID: 65, Speaker: "Jax", Text: "No, I want to see if we can spot the 'Mountain Man' from the forums."},
	{ID: 66, Speaker: "Leo", Text: "The one the locals say steals shoes?"},
	{ID: 67, Speaker: "Jax", Text: "Exactly! Think of the TikTok potential."},
	{ID: 68, Speaker: "Leo", Text: "I am not losing my $200 boots to a cryptid for your social media."},
	{ID: 69, Speaker: "Jax", Text: "You’re no fun."},
	{ID: 70, Speaker: "Leo", Text: "I’m 'safety-conscious.'"},
	{ID: 71, Speaker: "Jax", Text: "You’re 'terrified of fun.'"},
	{ID: 72, Speaker: "Leo", Text: "Fun doesn’t require a tetanus shot."},
	{ID: 73, Speaker: "Jax", Text: "Sometimes the best fun does!"},
	{ID: 74, Speaker: "Leo", Text: "That is a terrifying philosophy."},
	{ID: 75, Speaker: "Jax", Text: "It’s served me well for 25 years."},
	{ID: 76, Speaker: "Leo", Text: "You’ve broken six bones."},
	{ID: 77, Speaker: "Jax", Text: "And they all healed stronger!"},
	{ID: 78, Speaker: "Leo", Text: "That’s a medical myth, but I don’t have the energy to correct you."},
	{ID: 79, Speaker: "Jax", Text: "Success! Leo is giving up!"},
	{ID: 80, Speaker: "Leo", Text: "I’m not giving up, I’m conserving energy for the 'vertical scramble.'"},
	{ID: 81, Speaker: "Jax", Text: "Grab the beef jerky. The spicy kind."},
	{ID: 82, Speaker: "Leo", Text: "Sodium causes water retention. I’m bringing almonds."},
	{ID: 83, Speaker: "Jax", Text: "You’re like a squirrel. A very stressed squirrel."},
	{ID: 84, Speaker: "Leo", Text: "Squirrels are survivors, Jax."},
	{ID: 85, Speaker: "Jax", Text: "I’m more like a... golden retriever."},
	{ID: 86, Speaker: "Leo", Text: "A golden retriever that found a bag of coffee beans and a credit card."},
	{ID: 87, Speaker: "Jax", Text: "Best description of me ever. Put that on my headstone."},
	{ID: 88, Speaker: "Leo", Text: "Don’t talk about headstones when we’re headed to an 'unlisted' trail."},
	{ID: 89, Speaker: "Jax", Text: "Aww, you care about me!"},
	{ID: 90, Speaker: "Leo", Text: "I care about not filling out the paperwork for a missing person."},
	{ID: 91, Speaker: "Jax", Text: "Admit it. You’re excited."},
	{ID: 92, Speaker: "Leo", Text: "I am experiencing a moderate level of physiological arousal that could be interpreted as excitement."},
	{ID: 93, Speaker: "Jax", Text: "That’s a 'yes' in Leo-speak!"},
	{ID: 94, Speaker: "Leo", Text: "Just... promise me we won’t go off-trail."},
	{ID: 95, Speaker: "Jax", Text: "I promise to try to stay near the trail."},
	{ID: 96, Speaker: "Leo", Text: "That’s not a promise."},
	{ID: 97, Speaker: "Jax", Text: "It’s the best I can do."},
	{ID: 98, Speaker: "Jax", Text: "Bring three! Let’s party!"},
}
