-- +goose Up
ALTER TABLE message ALTER COLUMN parentId SET DEFAULT NULL;
ALTER TABLE GroupMessage ALTER COLUMN parent_id SET DEFAULT NULL;


-- +goose Down
ALTER TABLE message ALTER COLUMN parentId DROP DEFAULT;
ALTER TABLE GroupMessage ALTER COLUMN parent_id DROP DEFAULT;
